// This file was generated by counterfeiter
package fakefetcher

import (
	"sync"
	"time"
	. "github.com/cloudfoundry-incubator/nsync/bulk"
	"github.com/cloudfoundry-incubator/runtime-schema/models"
)

type FakeFetcher struct {
	FetchStub        func(chan<- models.DesiredLRP, time.Duration) error
	fetchMutex       sync.RWMutex
	fetchArgsForCall []struct {
		arg1 chan<- models.DesiredLRP
		arg2 time.Duration
	}
	fetchReturns struct {
		result1 error
	}
}

func (fake *FakeFetcher) Fetch(arg1 chan<- models.DesiredLRP, arg2 time.Duration) error {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.fetchArgsForCall = append(fake.fetchArgsForCall, struct {
		arg1 chan<- models.DesiredLRP
		arg2 time.Duration
	}{arg1, arg2})
	if fake.FetchStub != nil {
		return fake.FetchStub(arg1, arg2)
	} else {
		return fake.fetchReturns.result1
	}
}

func (fake *FakeFetcher) FetchCallCount() int {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return len(fake.fetchArgsForCall)
}

func (fake *FakeFetcher) FetchArgsForCall(i int) (chan<- models.DesiredLRP, time.Duration) {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return fake.fetchArgsForCall[i].arg1, fake.fetchArgsForCall[i].arg2
}

func (fake *FakeFetcher) FetchReturns(result1 error) {
	fake.fetchReturns = struct {
		result1 error
	}{result1}
}

var _ Fetcher = new(FakeFetcher)
