#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/Godeps/_workspace:$GOPATH

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

mkdir -p $FIRST_GOPATH/bin
export PATH=$FIRST_GOPATH/bin:$PATH

# lock down etcd to SHA in diego-release/src/etcd
# since latest code is very broken
# See: https://github.com/coreos/etcd/issues/986
go get -u github.com/coreos/etcd
pushd ${FIRST_GOPATH}/src/github.com/coreos/etcd
git checkout 0a2384bf4daec35a814244dc4d885e14f18b5ef1
popd
go install github.com/coreos/etcd

go get -u github.com/apcera/gnatsd
go get github.com/dustin/goveralls
go get code.google.com/p/go.tools/cmd/cover
go install github.com/onsi/ginkgo/ginkgo

ginkgo -cover -r -failOnPending -randomizeAllSpecs -race "$@"
