// This file was generated by counterfeiter
package fakes

import (
	"net/http"
	"sync"

	"github.com/cloudfoundry-incubator/nsync/bulk"
	"github.com/cloudfoundry-incubator/runtime-schema/cc_messages"
	"github.com/pivotal-golang/lager"
)

type FakeFetcher struct {
	FetchFingerprintsStub        func(logger lager.Logger, cancel <-chan struct{}, desiredAppFingerprints chan<- []cc_messages.CCDesiredAppFingerprint, httpClient *http.Client) error
	fetchFingerprintsMutex       sync.RWMutex
	fetchFingerprintsArgsForCall []struct {
		logger                 lager.Logger
		cancel                 <-chan struct{}
		desiredAppFingerprints chan<- []cc_messages.CCDesiredAppFingerprint
		httpClient             *http.Client
	}
	fetchFingerprintsReturns struct {
		result1 error
	}
	FetchDesiredLRPsStub        func(logger lager.Logger, cancel <-chan struct{}, desiredAppFingerprints <-chan []cc_messages.CCDesiredAppFingerprint, desireAppRequestsFromCC chan<- []cc_messages.DesireAppRequestFromCC, httpClient *http.Client) error
	fetchDesiredLRPsMutex       sync.RWMutex
	fetchDesiredLRPsArgsForCall []struct {
		logger                  lager.Logger
		cancel                  <-chan struct{}
		desiredAppFingerprints  <-chan []cc_messages.CCDesiredAppFingerprint
		desireAppRequestsFromCC chan<- []cc_messages.DesireAppRequestFromCC
		httpClient              *http.Client
	}
	fetchDesiredLRPsReturns struct {
		result1 error
	}
}

func (fake *FakeFetcher) FetchFingerprints(logger lager.Logger, cancel <-chan struct{}, desiredAppFingerprints chan<- []cc_messages.CCDesiredAppFingerprint, httpClient *http.Client) error {
	fake.fetchFingerprintsMutex.Lock()
	fake.fetchFingerprintsArgsForCall = append(fake.fetchFingerprintsArgsForCall, struct {
		logger                 lager.Logger
		cancel                 <-chan struct{}
		desiredAppFingerprints chan<- []cc_messages.CCDesiredAppFingerprint
		httpClient             *http.Client
	}{logger, cancel, desiredAppFingerprints, httpClient})
	fake.fetchFingerprintsMutex.Unlock()
	if fake.FetchFingerprintsStub != nil {
		return fake.FetchFingerprintsStub(logger, cancel, desiredAppFingerprints, httpClient)
	} else {
		return fake.fetchFingerprintsReturns.result1
	}
}

func (fake *FakeFetcher) FetchFingerprintsCallCount() int {
	fake.fetchFingerprintsMutex.RLock()
	defer fake.fetchFingerprintsMutex.RUnlock()
	return len(fake.fetchFingerprintsArgsForCall)
}

func (fake *FakeFetcher) FetchFingerprintsArgsForCall(i int) (lager.Logger, <-chan struct{}, chan<- []cc_messages.CCDesiredAppFingerprint, *http.Client) {
	fake.fetchFingerprintsMutex.RLock()
	defer fake.fetchFingerprintsMutex.RUnlock()
	return fake.fetchFingerprintsArgsForCall[i].logger, fake.fetchFingerprintsArgsForCall[i].cancel, fake.fetchFingerprintsArgsForCall[i].desiredAppFingerprints, fake.fetchFingerprintsArgsForCall[i].httpClient
}

func (fake *FakeFetcher) FetchFingerprintsReturns(result1 error) {
	fake.FetchFingerprintsStub = nil
	fake.fetchFingerprintsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeFetcher) FetchDesiredLRPs(logger lager.Logger, cancel <-chan struct{}, desiredAppFingerprints <-chan []cc_messages.CCDesiredAppFingerprint, desireAppRequestsFromCC chan<- []cc_messages.DesireAppRequestFromCC, httpClient *http.Client) error {
	fake.fetchDesiredLRPsMutex.Lock()
	fake.fetchDesiredLRPsArgsForCall = append(fake.fetchDesiredLRPsArgsForCall, struct {
		logger                  lager.Logger
		cancel                  <-chan struct{}
		desiredAppFingerprints  <-chan []cc_messages.CCDesiredAppFingerprint
		desireAppRequestsFromCC chan<- []cc_messages.DesireAppRequestFromCC
		httpClient              *http.Client
	}{logger, cancel, desiredAppFingerprints, desireAppRequestsFromCC, httpClient})
	fake.fetchDesiredLRPsMutex.Unlock()
	if fake.FetchDesiredLRPsStub != nil {
		return fake.FetchDesiredLRPsStub(logger, cancel, desiredAppFingerprints, desireAppRequestsFromCC, httpClient)
	} else {
		return fake.fetchDesiredLRPsReturns.result1
	}
}

func (fake *FakeFetcher) FetchDesiredLRPsCallCount() int {
	fake.fetchDesiredLRPsMutex.RLock()
	defer fake.fetchDesiredLRPsMutex.RUnlock()
	return len(fake.fetchDesiredLRPsArgsForCall)
}

func (fake *FakeFetcher) FetchDesiredLRPsArgsForCall(i int) (lager.Logger, <-chan struct{}, <-chan []cc_messages.CCDesiredAppFingerprint, chan<- []cc_messages.DesireAppRequestFromCC, *http.Client) {
	fake.fetchDesiredLRPsMutex.RLock()
	defer fake.fetchDesiredLRPsMutex.RUnlock()
	return fake.fetchDesiredLRPsArgsForCall[i].logger, fake.fetchDesiredLRPsArgsForCall[i].cancel, fake.fetchDesiredLRPsArgsForCall[i].desiredAppFingerprints, fake.fetchDesiredLRPsArgsForCall[i].desireAppRequestsFromCC, fake.fetchDesiredLRPsArgsForCall[i].httpClient
}

func (fake *FakeFetcher) FetchDesiredLRPsReturns(result1 error) {
	fake.FetchDesiredLRPsStub = nil
	fake.fetchDesiredLRPsReturns = struct {
		result1 error
	}{result1}
}

var _ bulk.Fetcher = new(FakeFetcher)
