// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/nsync/bulk"
	"github.com/cloudfoundry-incubator/runtime-schema/models"
)

type FakeRecipeBuilder struct {
	BuildStub        func(models.DesireAppRequestFromCC) (models.DesiredLRP, error)
	buildMutex       sync.RWMutex
	buildArgsForCall []struct {
		arg1 models.DesireAppRequestFromCC
	}
	buildReturns struct {
		result1 models.DesiredLRP
		result2 error
	}
}

func (fake *FakeRecipeBuilder) Build(arg1 models.DesireAppRequestFromCC) (models.DesiredLRP, error) {
	fake.buildMutex.Lock()
	defer fake.buildMutex.Unlock()
	fake.buildArgsForCall = append(fake.buildArgsForCall, struct {
		arg1 models.DesireAppRequestFromCC
	}{arg1})
	if fake.BuildStub != nil {
		return fake.BuildStub(arg1)
	} else {
		return fake.buildReturns.result1, fake.buildReturns.result2
	}
}

func (fake *FakeRecipeBuilder) BuildCallCount() int {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return len(fake.buildArgsForCall)
}

func (fake *FakeRecipeBuilder) BuildArgsForCall(i int) models.DesireAppRequestFromCC {
	fake.buildMutex.RLock()
	defer fake.buildMutex.RUnlock()
	return fake.buildArgsForCall[i].arg1
}

func (fake *FakeRecipeBuilder) BuildReturns(result1 models.DesiredLRP, result2 error) {
	fake.buildReturns = struct {
		result1 models.DesiredLRP
		result2 error
	}{result1, result2}
}

var _ bulk.RecipeBuilder = new(FakeRecipeBuilder)
